language: node_js
node_js:
  - '0.8'
  - '0.10'
before_script:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-salsa' ]; then cd .. && eval "mv $currentfolder generator-salsa" && cd generator-salsa; fi
  - npm install -g grunt-cli
